/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyPackage;

import pers.beans.Job;
import pers.dbutils.TaskAndJobDBOperations;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.border.BevelBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Amirk
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Search() {
        String role = Home.getRole();
        initComponents();
        ImageIcon myimage=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("TP_Logo.jpg")));
        
        Image img1=myimage.getImage();
        Image img2=img1.getScaledInstance(LOGO.getWidth(),LOGO.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i=new ImageIcon(img2);
        LOGO.setIcon(i);
        fillPageData();
        
        
    }
    private void fillPageData(){
        TaskAndJobDBOperations dBOperations = new TaskAndJobDBOperations();
        List<Job> list = dBOperations.getJobList("", new ArrayList<>());
        Object[][] data = new Object[list.size()][10];

        int count=1;
        for(int i=0;i<list.size();i++){
            Job bean = list.get(i);
            Object[] obj = new Object[10];
            obj[0]= bean.getJobID();
            obj[1]= bean.getUrgency();
            obj[2]= bean.getCustomerID();
            obj[3]= bean.getDeadline();
            obj[4] = bean.getSpecialInstruction();
            obj[5]= bean.getNumberOfTasksRemaining();
            obj[6] = bean.getDateCreated();
            obj[7] = bean.getPayByDate();
            obj[8] = bean.getEstimatedTimeRemaining();
            obj[9] = bean.getJobStatus();
            data[i] = obj;
        }

        DefaultTableModel tableModel =  new DefaultTableModel(data,
                new String[]{"Job ID", "Urgency", "CustomerID", "Deadline", "Special Instructions",
                        "No. Tasks Remaining", "Date Created", "Pay By Date"
                        , "Estimated Time Remaining", "Job Status"});
        jobTable.setModel(tableModel);
    }
    public void refreshTable(TaskAndJobDBOperations dBOperations, ResultSet set){
        List<Job> list = dBOperations.getJobList(set);
        updateBookingTable(dBOperations, list);
    }

    public void updateBookingTable(TaskAndJobDBOperations dBOperations, List<Job> list){
        Object[][] data = new Object[list.size()][];

        int count=1;
        String[] tableHeader = new String[]{"Job ID", "Urgency", "CustomerID", "Deadline", "Special Instructions",
                "No. Tasks Remaining", "Date Created", "Pay By Date"
                , "Estimated Time Remaining", "Job Status"};
        for(int i=0;i<list.size();i++){
            Job bean = list.get(i);
            Object[] obj = new Object[tableHeader.length];
            obj[0]= bean.getJobID();
            obj[1]= bean.getUrgency();
            obj[2]= bean.getCustomerID();
            obj[3]= bean.getDeadline();
            obj[4] = bean.getSpecialInstruction();
            obj[5]= bean.getNumberOfTasksRemaining();
            obj[6] = bean.getDateCreated();
            obj[7] = bean.getPayByDate();
            obj[8] = bean.getEstimatedTimeRemaining();
            obj[9] = bean.getJobStatus();
            data[i] = obj;
        }

        DefaultTableModel tableModel =  new DefaultTableModel(data,tableHeader);
        jobTable.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        LogoutBttn = new JButton();
        Exit = new JLabel();
        LOGO = new JLabel();
        jPanel2 = new JPanel();
        CustomerAccountBttn = new JButton();
        JobsBttn = new JButton();
        BackupBttn = new JButton();
        StaffBttn = new JButton();
        PaymentBttn = new JButton();
        jPanel3 = new JPanel();
        CreateJobsTitle = new JLabel();
        SearchBttn = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        Task = new JTextField();
        SpecialInstructions = new JTextField();
        Urgency = new JTextField();
        Deadline = new JTextField();
        jScrollPane1 = new JScrollPane();
        jobTable = new JTable();
        BackBttn = new JButton();
        JobID = new JTextField();
        CID = new JTextField();
        TasksL = new JTextField();
        PaidS = new JTextField();
        JobS = new JTextField();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        Date = new JTextField();
        jLabel10 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new Color(255, 51, 51));
        jPanel1.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        LogoutBttn.setText("Logout");
        LogoutBttn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                LogoutBttnActionPerformed(evt);
            }
        });

        Exit.setText("X");
        Exit.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        LOGO.setIcon(new ImageIcon(getClass().getResource("/MyPackage/TP_Logo.jpg"))); // NOI18N

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LOGO, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(Exit, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LogoutBttn, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Exit)
                .addGap(5, 5, 5)
                .addComponent(LogoutBttn, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(LOGO, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new Color(255, 51, 51));
        jPanel2.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        CustomerAccountBttn.setText("Customer");
        CustomerAccountBttn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                CustomerAccountBttnActionPerformed(evt);
            }
        });

        JobsBttn.setText("Jobs");
        JobsBttn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                JobsBttnActionPerformed(evt);
            }
        });

        BackupBttn.setText("Back-up/Restore");
        BackupBttn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                BackupBttnActionPerformed(evt);
            }
        });

        StaffBttn.setText("Staff");
        StaffBttn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                StaffBttnActionPerformed(evt);
            }
        });

        PaymentBttn.setText("Payment");
        PaymentBttn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                PaymentBttnActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustomerAccountBttn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JobsBttn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackupBttn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StaffBttn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PaymentBttn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 5, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(CustomerAccountBttn)
                .addGap(46, 46, 46)
                .addComponent(StaffBttn)
                .addGap(77, 77, 77)
                .addComponent(JobsBttn)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PaymentBttn)
                .addGap(92, 92, 92)
                .addComponent(BackupBttn)
                .addGap(78, 78, 78))
        );

        jPanel3.setBackground(new Color(255, 255, 255));
        jPanel3.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

        CreateJobsTitle.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        CreateJobsTitle.setHorizontalAlignment(SwingConstants.CENTER);
        CreateJobsTitle.setText("Search and View");

        SearchBttn.setText("Search");
        SearchBttn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                try {
                    SearchBttnActionPerformed(evt);
                } catch (SQLException throwables) {
                    throwables.printStackTrace();
                }
            }
        });

        jLabel1.setText("Task");

        jLabel2.setText("Special Instructions");

        jLabel3.setText("Urgency");

        jLabel4.setText("Deadline");

        Task.setText("Task...");
        Task.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                TaskMouseClicked(evt);
            }
        });
        Task.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                TaskActionPerformed(evt);
            }
        });

        SpecialInstructions.setText("Instructions");
        SpecialInstructions.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                SpecialInstructionsMouseClicked(evt);
            }
        });
        SpecialInstructions.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                SpecialInstructionsActionPerformed(evt);
            }
        });

        Urgency.setText("Urgency");
        Urgency.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                UrgencyMouseClicked(evt);
            }
        });

        Deadline.setText("Deadline");
        Deadline.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                DeadlineMouseClicked(evt);
            }
        });

        jobTable.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Task", "Special Instructions", "Urgency", "Deadline"
            }
        ));
        jScrollPane1.setViewportView(jobTable);

        BackBttn.setText("Back");
        BackBttn.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                BackBttnActionPerformed(evt);
            }
        });

        JobID.setText("Job ID");
        JobID.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                JobIDMouseClicked(evt);
            }
        });

        CID.setText("CustomerID");
        CID.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                CIDMouseClicked(evt);
            }
        });

        TasksL.setText("Tasks Left");
        TasksL.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                TasksLMouseClicked(evt);
            }
        });

        PaidS.setText("Status");
        PaidS.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                PaidSMouseClicked(evt);
            }
        });
        PaidS.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                PaidSActionPerformed(evt);
            }
        });

        JobS.setText("Status");
        JobS.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                JobSMouseClicked(evt);
            }
        });
        JobS.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                JobSActionPerformed(evt);
            }
        });

        jLabel5.setText("Job ID");

        jLabel6.setText("Customer ID");

        jLabel7.setText("Paid Status");

        jLabel8.setText("Tasks Left");

        jLabel9.setText("Job Status");

        Date.setText("Date");
        Date.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                DateMouseClicked(evt);
            }
        });
        Date.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        jLabel10.setText("Date");

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreateJobsTitle, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackBttn)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(CID, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Deadline, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(35, 35, 35))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(JobID)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(Urgency, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(SpecialInstructions)
                                    .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TasksL))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(PaidS, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(Task, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(Date, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(JobS, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(SearchBttn))
                                            .addComponent(jLabel9)))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 696, GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(CreateJobsTitle, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(Urgency, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(JobS, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(JobID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpecialInstructions, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchBttn))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BackBttn)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(TasksL, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                    .addComponent(Task, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaidS, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                    .addComponent(CID, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deadline, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 409, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void BackupBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackupBttnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Backup().setVisible(true);
    }//GEN-LAST:event_BackupBttnActionPerformed

    private void LogoutBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBttnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_LogoutBttnActionPerformed

    private void JobsBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobsBttnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Jobs().setVisible(true);
    }//GEN-LAST:event_JobsBttnActionPerformed

    private void CustomerAccountBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerAccountBttnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ManageCustomers().setVisible(true);
    }//GEN-LAST:event_CustomerAccountBttnActionPerformed

    private void SearchBttnActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_CreateBttnActionPerformed
        // TODO add your handling code here: create should update newjobs table and also show up on jobs within new jobs table. need to do when connecting
        String Tasks = null;
        String SpecialI = null;
        String Urg = null;
        LocalDate deadLine = null;
        int JobsID = -1;
        int CustomerID = -1;
        int TasksLeft = -1;
        String PaidStatus = null;
        String JobStatus = null;

        LocalDate dateCreated = null;
        LocalDate payByDate = null;

        if(!Task.getText().equals("")) {Tasks = Task.getText(); }
        if (!SpecialInstructions.getText().equals("")) {SpecialI = SpecialInstructions.getText();}
        if (!Urgency.getText().equals("")) {
            Urg = Urgency.getText();
        }
        if (!Deadline.getText().equals("")) {
            String DeadL = Deadline.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            deadLine = LocalDate.parse(DeadL, formatter);

        }
        if (!JobID.getText().equals("")){
            JobsID = Integer.parseInt(JobID.getText());
        }
        if (!CID.getText().equals("")) {
            CustomerID = Integer.parseInt(CID.getText());
        }
        if (!TasksL.getText().equals("")) {
            TasksLeft = Integer.parseInt(TasksL.getText());
        }
        if (!PaidS.getText().equals("")) {
            PaidStatus = PaidS.getText();
        }
        if (!JobS.getText().equals("")) {
            JobStatus = JobS.getText();
        }

        TaskAndJobDBOperations dBOperations = new TaskAndJobDBOperations();

        ResultSet set = dBOperations.SearchJob(JobsID,CustomerID,Urg,deadLine,SpecialI, TasksLeft, dateCreated, PaidStatus, payByDate);
        refreshTable(dBOperations ,set);

    }//GEN-LAST:event_CreateBttnActionPerformed

    private void SpecialInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialInstructionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecialInstructionsActionPerformed

    private void TaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskActionPerformed

    private void BackBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBttnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Jobs().setVisible(true);
    }//GEN-LAST:event_BackBttnActionPerformed

    private void JobSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JobSActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void JobIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobIDMouseClicked
        // TODO add your handling code here:
        JobID.setText("");
    }//GEN-LAST:event_JobIDMouseClicked

    private void CIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CIDMouseClicked
        // TODO add your handling code here:
        CID.setText("");
    }//GEN-LAST:event_CIDMouseClicked

    private void UrgencyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UrgencyMouseClicked
        // TODO add your handling code here:
        Urgency.setText("");
    }//GEN-LAST:event_UrgencyMouseClicked

    private void DeadlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeadlineMouseClicked
        // TODO add your handling code here:
        Deadline.setText("");
    }//GEN-LAST:event_DeadlineMouseClicked

    private void SpecialInstructionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpecialInstructionsMouseClicked
        // TODO add your handling code here:
        SpecialInstructions.setText("");
    }//GEN-LAST:event_SpecialInstructionsMouseClicked

    private void TasksLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TasksLMouseClicked
        // TODO add your handling code here:
        TasksL.setText("");
    }//GEN-LAST:event_TasksLMouseClicked

    private void DateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateMouseClicked
        // TODO add your handling code here:
        Date.setText("");
    }//GEN-LAST:event_DateMouseClicked

    private void PaidSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaidSMouseClicked
        // TODO add your handling code here:
        PaidS.setText("");
    }//GEN-LAST:event_PaidSMouseClicked

    private void JobSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JobSMouseClicked
        // TODO add your handling code here:
        JobS.setText("");
    }//GEN-LAST:event_JobSMouseClicked

    private void TaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskMouseClicked
        // TODO add your handling code here:
        Task.setText("");
    }//GEN-LAST:event_TaskMouseClicked

    private void StaffBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffBttnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ManageStaff().setVisible(true);
    }//GEN-LAST:event_StaffBttnActionPerformed

    private void PaymentBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentBttnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Payment().setVisible(true);
    }//GEN-LAST:event_PaymentBttnActionPerformed

    private void PaidSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaidSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaidSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBttn;
    private javax.swing.JButton BackupBttn;
    private javax.swing.JTextField CID;
    private javax.swing.JLabel CreateJobsTitle;
    private javax.swing.JButton CustomerAccountBttn;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Deadline;
    private javax.swing.JLabel Exit;
    private javax.swing.JTextField JobID;
    private javax.swing.JTextField JobS;
    private javax.swing.JButton JobsBttn;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton LogoutBttn;
    private javax.swing.JTextField PaidS;
    private javax.swing.JButton PaymentBttn;
    private javax.swing.JButton SearchBttn;
    private javax.swing.JTextField SpecialInstructions;
    private javax.swing.JButton StaffBttn;
    private javax.swing.JTextField Task;
    private javax.swing.JTextField TasksL;
    private javax.swing.JTextField Urgency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jobTable;
    // End of variables declaration//GEN-END:variables
}
